name: Andre
options:
  bundleIdPrefix: com.andre
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

packages:
  AndreApp:
    path: AndreApp

targets:
  Andre:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: Andre
        excludes:
          - "**/*.md"

    dependencies:
      - package: AndreApp

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andre.app
        PRODUCT_NAME: Andre
        INFOPLIST_FILE: Andre/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: '"Andre/Preview Content"'
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: -O

    scheme:
      testTargets:
        - AndreTests
      gatherCoverageData: true

    preBuildScripts:
      - script: |
          # SwiftLint
          if which swiftlint >/dev/null; then
            swiftlint
          fi
        name: SwiftLint
        runOnlyWhenInstalling: false
        showEnvVars: false

  AndreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AndreTests
    dependencies:
      - target: Andre
      - package: AndreApp

schemes:
  Andre:
    build:
      targets:
        Andre: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - AndreTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
